### ISSUE TITLE
null_safety_branch

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#1291]
when compiling the current branch and starting the app:

Syncing files to device sdk gphone x86...

======== Exception caught by widgets library =======================================================
The following assertion was thrown building AppBuilder(dirty, state: AppBuilderState#70839):
'package:flutter/src/material/theme_data.dart': Failed assertion: line 483 pos 12: 'colorScheme?.brightness == null || brightness == null || colorScheme!.brightness == brightness': is not true.

**Comment by S-Man42** [comment]
Yes, can confirm this. Full Stacktrace:

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building AppBuilder(dirty, state: AppBuilderState#e2185):
'package:flutter/src/material/theme_data.dart': Failed assertion: line 483 pos 12: 'colorScheme?.brightness == null || brightness == null || colorScheme!.brightness == brightness': is not true.

The relevant error-causing widget was: 
  AppBuilder AppBuilder:file:///E:/workspace/GCWizard/lib/main.dart:39:18
When the exception was thrown, this was the stack: 
#2      new ThemeData (package:flutter/src/material/theme_data.dart:483:12)
#3      buildTheme (package:gc_wizard/application/theme/theme.dart:65:10)
#4      App.build.<anonymous closure>.<anonymous closure> (package:gc_wizard/main.dart:50:22)
#5      AppBuilderState.build (package:gc_wizard/application/app_builder.dart:25:26)
#6      StatefulElement.build (package:flutter/src/widgets/framework.dart:5080:27)
```
