### ISSUE TITLE
Coordinates: Cannot Input Location

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#581]
The "own location button" doesn't work anymore after https://github.com/S-Man42/GCWizard/pull/492

`gcw_coords.dar`t line 458 changed from` LatLng(...)` to `DEC(...)` which is not supported by the Input Location function. Needs work here!

**Comment by S-Man42** [comment]
It's even heavier... Nearly no coord calculation is executable:

```
======== Exception caught by widgets ===============================================================
The following _TypeError was thrown while calling onChanged:
type 'DMM' is not a subtype of type 'LatLng'

When the exception was thrown, this was the stack: 
#0      AntipodesState.build.<anonymous closure>.<anonymous closure> (package:gc_wizard/widgets/tools/coords/antipodes.dart:39:15)
#1      State.setState (package:flutter/src/widgets/framework.dart:1267:30)
#2      AntipodesState.build.<anonymous closure> (package:gc_wizard/widgets/tools/coords/antipodes.dart:37:13)
#3      GCWCoordsState._setCurrentValueAndEmitOnChange (package:gc_wizard/widgets/tools/coords/base/gcw_coords.dart:372:21)
#4      GCWCoordsState.build.<anonymous closure>.<anonymous closure> (package:gc_wizard/widgets/tools/coords/base/gcw_coords.dart:98:15)
...
====================================================================================================
```
