### ISSUE TITLE
Exif Viewer: "open thumbnail in exif viewer" -> Null Pointer Exception

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#601]
Example Picture
![20210601_203505 1](https://user-images.githubusercontent.com/16626063/120500946-80169480-c3c1-11eb-95c0-10c4aa860a50.jpg)

**Comment by ludoo0d0a** [comment]
reproduced.
Crashed in image 3.0.2 plugin itself

```

E/flutter ( 7971): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 7971): #0      JpegScan._decodeBaseline (package:image/src/formats/jpeg/jpeg_scan.dart:189:58)
E/flutter ( 7971): #1      JpegScan._decodeMcu (package:image/src/formats/jpeg/jpeg_scan.dart:328:13)
E/flutter ( 7971): #2      JpegScan.decode (package:image/src/formats/jpeg/jpeg_scan.dart:99:17)
E/flutter ( 7971): #3      JpegData._readSOS (package:image/src/formats/jpeg/jpeg_data.dart:605:10)
E/flutter ( 7971): #4      JpegData._read (package:image/src/formats/jpeg/jpeg_data.dart:206:11)
E/flutter ( 7971): #5      JpegData.read (package:image/src/formats/jpeg/jpeg_data.dart:119:5)
E/flutter ( 7971): #6      JpegDecoder.decodeImage (package:image/src/formats/jpeg_decoder.dart:46:10)
E/flutter ( 7971): #7      decodeImage (package:image/src/formats/formats.dart:92:18)
E/flutter ( 7971): #8      _ExifReaderState.completeImageMetadata (package:gc_wizard/widgets/tools/images_and_files/exif_reader.dart:231:12)
E/flutter ( 7971): #9      _ExifReaderState._readFile (package:gc_wizard/widgets/tools/images_and_files/exif_reader.dart:89:20)
E/flutter ( 7971): <asynchronous suspension>
```

**Comment by ludoo0d0a** [comment]
PR #609
